[package]
name = "rustcoder"
version = "0.1.0"
edition = "2021"
author = ["ryuma017 <tgcrym01@gmail.com>"]
description = "Convenient toolchain for AtCoder written in Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.6", features = ["derive"] }
reqwest = "0.11"
tokio = { version = "1.17.0", features = ["full"] }
